# Generated by Django 4.1.4 on 2023-02-13 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.AutoField(db_column='Id', db_index=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('types', models.TextField(blank=True, db_column='Types', db_index=True, null=True)),
            ],
            options={
                'db_table': 'Keys',
            },
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('postalcode', models.TextField(blank=True, db_column='PostalCode', null=True)),
                ('fulladdress', models.TextField(blank=True, db_column='FullAddress', null=True)),
                ('status', models.IntegerField(db_column='status', db_index=True, default=0)),
                ('condition', models.IntegerField(db_column='Condition', db_index=True, default=0)),
                ('signature', models.ImageField(blank=True, db_column='Signature', null=True, upload_to='props/signatures/')),
                ('signature_name', models.CharField(blank=True, db_column='SignatureName', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='Propertytypes',
            fields=[
                ('id', models.AutoField(db_column='Id', db_index=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('types', models.TextField(blank=True, db_column='Types', db_index=True, null=True)),
            ],
            options={
                'db_table': 'PropertyTypes',
            },
        ),
        migrations.CreateModel(
            name='Propertykeys',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField(blank=True, db_column='Count', null=True)),
                ('keysid', models.ForeignKey(db_column='KeysId', on_delete=django.db.models.deletion.CASCADE, to='props.keys')),
                ('propertiesid', models.ForeignKey(db_column='PropertiesId', on_delete=django.db.models.deletion.CASCADE, to='props.properties')),
            ],
            options={
                'db_table': 'PropertyKeys',
            },
        ),
        migrations.CreateModel(
            name='PropertyComment',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True, db_column='Comment', db_index=True, null=True)),
                ('property_id', models.ForeignKey(blank=True, db_column='PropertyId', null=True, on_delete=django.db.models.deletion.CASCADE, to='props.properties')),
            ],
            options={
                'db_table': 'PropertyComment',
            },
        ),
        migrations.AddField(
            model_name='properties',
            name='propertytypesid',
            field=models.ForeignKey(db_column='PropertyTypesId', on_delete=django.db.models.deletion.CASCADE, to='props.propertytypes'),
        ),
        migrations.AddField(
            model_name='properties',
            name='userslandlordid',
            field=models.ForeignKey(blank=True, db_column='UsersLandlordId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_landlord_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='properties',
            name='usersownerid',
            field=models.ForeignKey(blank=True, db_column='UsersOwnerId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_owner_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='properties',
            name='userstenantid',
            field=models.ForeignKey(blank=True, db_column='UsersTenantId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_tenant_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Meterstypes',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meters', models.TextField(blank=True, db_column='Meters', db_index=True, null=True)),
                ('is_default', models.BooleanField(blank=True, db_column='IsDefault', db_index=True, null=True)),
                ('user_id', models.ForeignKey(blank=True, db_column='userId', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'MetersTypes',
            },
        ),
        migrations.CreateModel(
            name='Meterreading',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metervalue', models.TextField(blank=True, db_column='MeterValue', null=True)),
                ('pictureurl', models.ImageField(blank=True, db_column='PictureURL', null=True, upload_to='props/meters/')),
                ('meterstypesid', models.ForeignKey(db_column='MetersTypesId', on_delete=django.db.models.deletion.CASCADE, to='props.meterstypes')),
                ('propertiesid', models.ForeignKey(db_column='PropertiesId', on_delete=django.db.models.deletion.CASCADE, to='props.properties')),
            ],
            options={
                'db_table': 'MeterReading',
            },
        ),
    ]
