# Generated by Django 4.0.6 on 2022-07-17 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Furnitures',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('isactive', models.BooleanField(db_column='IsActive')),
                ('regdate', models.CharField(blank=True, db_column='RegDate', max_length=10, null=True)),
                ('furniture', models.TextField(blank=True, db_column='Furniture', null=True)),
            ],
            options={
                'db_table': 'Furnitures',
            },
        ),
        migrations.CreateModel(
            name='Furnituresinrooms',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('isactive', models.BooleanField(db_column='IsActive')),
                ('regdate', models.CharField(blank=True, db_column='RegDate', max_length=10, null=True)),
                ('quantity', models.IntegerField(db_column='Quantity')),
                ('furnituresid', models.ForeignKey(db_column='FurnituresId', on_delete=django.db.models.deletion.DO_NOTHING, to='props.furnitures')),
            ],
            options={
                'db_table': 'FurnituresInRooms',
            },
        ),
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('isactive', models.BooleanField(db_column='IsActive')),
                ('regdate', models.CharField(blank=True, db_column='RegDate', max_length=10, null=True)),
                ('types', models.TextField(blank=True, db_column='Types', null=True)),
            ],
            options={
                'db_table': 'Keys',
            },
        ),
        migrations.CreateModel(
            name='Meterstypes',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('isactive', models.BooleanField(db_column='IsActive')),
                ('regdate', models.CharField(blank=True, db_column='RegDate', max_length=10, null=True)),
                ('meters', models.TextField(blank=True, db_column='Meters', null=True)),
            ],
            options={
                'db_table': 'MetersTypes',
            },
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('isactive', models.BooleanField(db_column='IsActive')),
                ('regdate', models.CharField(blank=True, db_column='RegDate', max_length=10, null=True)),
                ('postalcode', models.TextField(blank=True, db_column='PostalCode', null=True)),
                ('fulladdress', models.TextField(blank=True, db_column='FullAddress', null=True)),
                ('condition', models.IntegerField(db_column='Condition')),
            ],
            options={
                'db_table': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='Propertytypes',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('isactive', models.BooleanField(db_column='IsActive')),
                ('regdate', models.CharField(blank=True, db_column='RegDate', max_length=10, null=True)),
                ('types', models.TextField(blank=True, db_column='Types', null=True)),
            ],
            options={
                'db_table': 'PropertyTypes',
            },
        ),
        migrations.CreateModel(
            name='Roomtypes',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('isactive', models.BooleanField(db_column='IsActive')),
                ('regdate', models.CharField(blank=True, db_column='RegDate', max_length=10, null=True)),
                ('types', models.TextField(blank=True, db_column='Types', null=True)),
            ],
            options={
                'db_table': 'RoomTypes',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('isactive', models.BooleanField(db_column='IsActive')),
                ('regdate', models.CharField(blank=True, db_column='RegDate', max_length=10, null=True)),
                ('roomtitle', models.TextField(blank=True, db_column='RoomTitle', null=True)),
                ('propertiesid', models.ForeignKey(db_column='PropertiesId', on_delete=django.db.models.deletion.DO_NOTHING, to='props.properties')),
                ('roomtypesid', models.ForeignKey(db_column='RoomTypesId', on_delete=django.db.models.deletion.DO_NOTHING, to='props.roomtypes')),
            ],
            options={
                'db_table': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='Roompictures',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('isactive', models.BooleanField(db_column='IsActive')),
                ('regdate', models.CharField(blank=True, db_column='RegDate', max_length=10, null=True)),
                ('url', models.TextField(blank=True, db_column='URL', null=True)),
                ('roomsid', models.ForeignKey(db_column='RoomsId', on_delete=django.db.models.deletion.DO_NOTHING, to='props.rooms')),
            ],
            options={
                'db_table': 'RoomPictures',
            },
        ),
        migrations.CreateModel(
            name='Propertykeys',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('isactive', models.BooleanField(db_column='IsActive')),
                ('regdate', models.CharField(blank=True, db_column='RegDate', max_length=10, null=True)),
                ('pictureurl', models.TextField(blank=True, db_column='PictureURL', null=True)),
                ('keysid', models.ForeignKey(db_column='KeysId', on_delete=django.db.models.deletion.DO_NOTHING, to='props.keys')),
                ('propertiesid', models.ForeignKey(db_column='PropertiesId', on_delete=django.db.models.deletion.DO_NOTHING, to='props.properties')),
            ],
            options={
                'db_table': 'PropertyKeys',
            },
        ),
        migrations.AddField(
            model_name='properties',
            name='propertytypesid',
            field=models.ForeignKey(db_column='PropertyTypesId', on_delete=django.db.models.deletion.DO_NOTHING, to='props.propertytypes'),
        ),
        migrations.AddField(
            model_name='properties',
            name='userslandlordid',
            field=models.ForeignKey(db_column='UsersLandlordId', on_delete=django.db.models.deletion.DO_NOTHING, related_name='User_landlord_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='properties',
            name='usersownerid',
            field=models.ForeignKey(db_column='UsersOwnerId', on_delete=django.db.models.deletion.DO_NOTHING, related_name='User_owner_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='properties',
            name='userstenantid',
            field=models.ForeignKey(db_column='UsersTenantId', on_delete=django.db.models.deletion.DO_NOTHING, related_name='User_tenant_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Meterreading',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('isactive', models.BooleanField(db_column='IsActive')),
                ('regdate', models.CharField(blank=True, db_column='RegDate', max_length=10, null=True)),
                ('metervalue', models.TextField(blank=True, db_column='MeterValue', null=True)),
                ('pictureurl', models.TextField(blank=True, db_column='PictureURL', null=True)),
                ('meterstypesid', models.ForeignKey(db_column='MetersTypesId', on_delete=django.db.models.deletion.DO_NOTHING, to='props.meterstypes')),
                ('propertiesid', models.ForeignKey(db_column='PropertiesId', on_delete=django.db.models.deletion.DO_NOTHING, to='props.properties')),
            ],
            options={
                'db_table': 'MeterReading',
            },
        ),
        migrations.CreateModel(
            name='Furnituresinroomspictures',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('isactive', models.BooleanField(db_column='IsActive')),
                ('regdate', models.CharField(blank=True, db_column='RegDate', max_length=10, null=True)),
                ('url', models.TextField(blank=True, db_column='URL', null=True)),
                ('furnituresinroomsid', models.ForeignKey(db_column='FurnituresInRoomsId', on_delete=django.db.models.deletion.DO_NOTHING, to='props.furnituresinrooms')),
            ],
            options={
                'db_table': 'FurnituresInRoomsPictures',
            },
        ),
        migrations.AddField(
            model_name='furnituresinrooms',
            name='roomsid',
            field=models.ForeignKey(db_column='RoomsId', on_delete=django.db.models.deletion.DO_NOTHING, to='props.rooms'),
        ),
        migrations.AddField(
            model_name='furnitures',
            name='roomtypesid',
            field=models.ForeignKey(db_column='RoomTypesId', on_delete=django.db.models.deletion.DO_NOTHING, to='props.roomtypes'),
        ),
    ]
