# Generated by Django 4.0.6 on 2022-07-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Furnitures',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('isactive', models.BooleanField(db_column='IsActive')),
                ('regdate', models.CharField(blank=True, db_column='RegDate', max_length=10, null=True)),
                ('furniture', models.TextField(blank=True, db_column='Furniture', null=True)),
            ],
            options={
                'db_table': 'Furnitures',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Furnituresinrooms',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('isactive', models.BooleanField(db_column='IsActive')),
                ('regdate', models.CharField(blank=True, db_column='RegDate', max_length=10, null=True)),
                ('quantity', models.IntegerField(db_column='Quantity')),
            ],
            options={
                'db_table': 'FurnituresInRooms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Furnituresinroomspictures',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('isactive', models.BooleanField(db_column='IsActive')),
                ('regdate', models.CharField(blank=True, db_column='RegDate', max_length=10, null=True)),
                ('url', models.TextField(blank=True, db_column='URL', null=True)),
            ],
            options={
                'db_table': 'FurnituresInRoomsPictures',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('isactive', models.BooleanField(db_column='IsActive')),
                ('regdate', models.CharField(blank=True, db_column='RegDate', max_length=10, null=True)),
                ('types', models.TextField(blank=True, db_column='Types', null=True)),
            ],
            options={
                'db_table': 'Keys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Meterreading',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('isactive', models.BooleanField(db_column='IsActive')),
                ('regdate', models.CharField(blank=True, db_column='RegDate', max_length=10, null=True)),
                ('metervalue', models.TextField(blank=True, db_column='MeterValue', null=True)),
                ('pictureurl', models.TextField(blank=True, db_column='PictureURL', null=True)),
            ],
            options={
                'db_table': 'MeterReading',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Meterstypes',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('isactive', models.BooleanField(db_column='IsActive')),
                ('regdate', models.CharField(blank=True, db_column='RegDate', max_length=10, null=True)),
                ('meters', models.TextField(blank=True, db_column='Meters', null=True)),
            ],
            options={
                'db_table': 'MetersTypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('isactive', models.BooleanField(db_column='IsActive')),
                ('regdate', models.CharField(blank=True, db_column='RegDate', max_length=10, null=True)),
                ('postalcode', models.TextField(blank=True, db_column='PostalCode', null=True)),
                ('fulladdress', models.TextField(blank=True, db_column='FullAddress', null=True)),
                ('condition', models.IntegerField(db_column='Condition')),
            ],
            options={
                'db_table': 'Properties',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Propertykeys',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('isactive', models.BooleanField(db_column='IsActive')),
                ('regdate', models.CharField(blank=True, db_column='RegDate', max_length=10, null=True)),
                ('pictureurl', models.TextField(blank=True, db_column='PictureURL', null=True)),
            ],
            options={
                'db_table': 'PropertyKeys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Propertytypes',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('isactive', models.BooleanField(db_column='IsActive')),
                ('regdate', models.CharField(blank=True, db_column='RegDate', max_length=10, null=True)),
                ('types', models.TextField(blank=True, db_column='Types', null=True)),
            ],
            options={
                'db_table': 'PropertyTypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roompictures',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('isactive', models.BooleanField(db_column='IsActive')),
                ('regdate', models.CharField(blank=True, db_column='RegDate', max_length=10, null=True)),
                ('url', models.TextField(blank=True, db_column='URL', null=True)),
            ],
            options={
                'db_table': 'RoomPictures',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('isactive', models.BooleanField(db_column='IsActive')),
                ('regdate', models.CharField(blank=True, db_column='RegDate', max_length=10, null=True)),
                ('roomtitle', models.TextField(blank=True, db_column='RoomTitle', null=True)),
            ],
            options={
                'db_table': 'Rooms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roomtypes',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('isactive', models.BooleanField(db_column='IsActive')),
                ('regdate', models.CharField(blank=True, db_column='RegDate', max_length=10, null=True)),
                ('types', models.TextField(blank=True, db_column='Types', null=True)),
            ],
            options={
                'db_table': 'RoomTypes',
                'managed': False,
            },
        ),
    ]
