# Generated by Django 4.0.6 on 2022-07-17 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertytypes',
            name='image',
            field=models.ImageField(blank=True, db_column='Image', null=True, upload_to='media/'),
        ),
    ]
