# Generated by Django 4.0.6 on 2022-09-05 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('props', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='userslandlordid',
            field=models.ForeignKey(blank=True, db_column='UsersLandlordId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_landlord_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='properties',
            name='usersownerid',
            field=models.ForeignKey(blank=True, db_column='UsersOwnerId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_owner_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='properties',
            name='userstenantid',
            field=models.ForeignKey(blank=True, db_column='UsersTenantId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_tenant_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
