# Generated by Django 4.1.4 on 2023-02-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='condition',
            field=models.IntegerField(db_column='Condition', db_index=True, default=1),
        ),
    ]
