# Generated by Django 4.0.6 on 2022-09-17 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0002_alter_properties_userslandlordid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertykeys',
            name='pictureurl',
        ),
        migrations.AddField(
            model_name='propertykeys',
            name='count',
            field=models.IntegerField(blank=True, db_column='Count', null=True),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='pictureurl',
            field=models.ImageField(blank=True, db_column='PictureURL', null=True, upload_to='props/'),
        ),
        migrations.AlterField(
            model_name='propertytypes',
            name='pictureurl',
            field=models.ImageField(blank=True, db_column='PictureURL', null=True, upload_to='props/'),
        ),
    ]
