# Generated by Django 4.1.4 on 2023-02-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0002_alter_properties_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='properties',
            old_name='signature',
            new_name='landlord_signature',
        ),
        migrations.RenameField(
            model_name='properties',
            old_name='signature_name',
            new_name='landlord_signature_name',
        ),
        migrations.AddField(
            model_name='properties',
            name='tenant_signature',
            field=models.ImageField(blank=True, db_column='T_Signature', null=True, upload_to='props/signatures/'),
        ),
        migrations.AddField(
            model_name='properties',
            name='tenant_signature_name',
            field=models.CharField(blank=True, db_column='T_SignatureName', max_length=100, null=True),
        ),
    ]
