# Generated by Django 4.0.6 on 2022-07-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0002_propertytypes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnitures',
            name='regdate',
            field=models.DateField(blank=True, db_column='RegDate', null=True),
        ),
        migrations.AlterField(
            model_name='furnituresinrooms',
            name='regdate',
            field=models.DateField(blank=True, db_column='RegDate', null=True),
        ),
        migrations.AlterField(
            model_name='furnituresinroomspictures',
            name='regdate',
            field=models.DateField(blank=True, db_column='RegDate', null=True),
        ),
        migrations.AlterField(
            model_name='keys',
            name='regdate',
            field=models.DateField(blank=True, db_column='RegDate', null=True),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='regdate',
            field=models.DateField(blank=True, db_column='RegDate', null=True),
        ),
        migrations.AlterField(
            model_name='meterstypes',
            name='regdate',
            field=models.DateField(blank=True, db_column='RegDate', null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='regdate',
            field=models.DateField(blank=True, db_column='RegDate', null=True),
        ),
        migrations.AlterField(
            model_name='propertykeys',
            name='regdate',
            field=models.DateField(blank=True, db_column='RegDate', null=True),
        ),
        migrations.AlterField(
            model_name='propertytypes',
            name='regdate',
            field=models.DateField(blank=True, db_column='RegDate', null=True),
        ),
        migrations.AlterField(
            model_name='roompictures',
            name='regdate',
            field=models.DateField(blank=True, db_column='RegDate', null=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='regdate',
            field=models.DateField(blank=True, db_column='RegDate', null=True),
        ),
        migrations.AlterField(
            model_name='roomtypes',
            name='regdate',
            field=models.DateField(blank=True, db_column='RegDate', null=True),
        ),
    ]
