# Generated by Django 4.0.6 on 2022-09-17 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0003_remove_propertykeys_pictureurl_propertykeys_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertytypes',
            name='pictureurl',
        ),
    ]
