# Generated by Django 4.0.6 on 2022-07-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0003_alter_furnitures_regdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertytypes',
            name='image',
        ),
        migrations.AddField(
            model_name='propertytypes',
            name='pictureurl',
            field=models.ImageField(blank=True, db_column='PictureURL', null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='pictureurl',
            field=models.ImageField(blank=True, db_column='PictureURL', null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='propertykeys',
            name='pictureurl',
            field=models.ImageField(blank=True, db_column='PictureURL', null=True, upload_to='media/'),
        ),
    ]
