# Generated by Django 4.1.4 on 2023-02-28 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('props', '0003_rename_signature_properties_landlord_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertycomment',
            name='user',
            field=models.ForeignKey(blank=True, db_column='userId', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
