# Generated by Django 4.1.4 on 2023-02-28 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0004_propertycomment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertycomment',
            old_name='property_id',
            new_name='property',
        ),
    ]
