# Generated by Django 4.0.6 on 2022-07-18 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0004_remove_propertytypes_image_propertytypes_pictureurl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furnituresinrooms',
            name='furnituresid',
        ),
        migrations.RemoveField(
            model_name='furnituresinrooms',
            name='roomsid',
        ),
        migrations.RemoveField(
            model_name='furnituresinroomspictures',
            name='furnituresinroomsid',
        ),
        migrations.RemoveField(
            model_name='roompictures',
            name='roomsid',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='propertiesid',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='roomtypesid',
        ),
        migrations.DeleteModel(
            name='Furnitures',
        ),
        migrations.DeleteModel(
            name='Furnituresinrooms',
        ),
        migrations.DeleteModel(
            name='Furnituresinroomspictures',
        ),
        migrations.DeleteModel(
            name='Roompictures',
        ),
        migrations.DeleteModel(
            name='Rooms',
        ),
        migrations.DeleteModel(
            name='Roomtypes',
        ),
    ]
