# Generated by Django 4.0.6 on 2022-09-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0004_remove_propertytypes_pictureurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='pictureurl',
            field=models.ImageField(blank=True, db_column='PictureURL', null=True, upload_to='props/meters/'),
        ),
    ]
