# Generated by Django 4.0.6 on 2022-07-20 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('props', '0005_remove_furnituresinrooms_furnituresid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterstypes',
            name='is_default',
            field=models.BooleanField(blank=True, db_column='IsDefault', null=True),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='meterstypesid',
            field=models.ForeignKey(db_column='MetersTypesId', on_delete=django.db.models.deletion.CASCADE, to='props.meterstypes'),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='propertiesid',
            field=models.ForeignKey(db_column='PropertiesId', on_delete=django.db.models.deletion.CASCADE, to='props.properties'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='propertytypesid',
            field=models.ForeignKey(db_column='PropertyTypesId', on_delete=django.db.models.deletion.CASCADE, to='props.propertytypes'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='userslandlordid',
            field=models.ForeignKey(db_column='UsersLandlordId', on_delete=django.db.models.deletion.CASCADE, related_name='User_landlord_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='properties',
            name='usersownerid',
            field=models.ForeignKey(db_column='UsersOwnerId', on_delete=django.db.models.deletion.CASCADE, related_name='User_owner_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='properties',
            name='userstenantid',
            field=models.ForeignKey(db_column='UsersTenantId', on_delete=django.db.models.deletion.CASCADE, related_name='User_tenant_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertykeys',
            name='keysid',
            field=models.ForeignKey(db_column='KeysId', on_delete=django.db.models.deletion.CASCADE, to='props.keys'),
        ),
        migrations.AlterField(
            model_name='propertykeys',
            name='propertiesid',
            field=models.ForeignKey(db_column='PropertiesId', on_delete=django.db.models.deletion.CASCADE, to='props.properties'),
        ),
        migrations.CreateModel(
            name='PropertyStatus',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('isactive', models.BooleanField(db_column='IsActive')),
                ('regdate', models.DateField(blank=True, db_column='RegDate', null=True)),
                ('comment', models.TextField(blank=True, db_column='Comment', null=True)),
                ('property_id', models.ForeignKey(blank=True, db_column='PropertyId', null=True, on_delete=django.db.models.deletion.CASCADE, to='props.properties')),
            ],
            options={
                'db_table': 'PropertyStatus',
            },
        ),
        migrations.CreateModel(
            name='PropertyComment',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('isactive', models.BooleanField(db_column='IsActive')),
                ('regdate', models.DateField(blank=True, db_column='RegDate', null=True)),
                ('comment', models.TextField(blank=True, db_column='Comment', null=True)),
                ('property_id', models.ForeignKey(blank=True, db_column='PropertyId', null=True, on_delete=django.db.models.deletion.CASCADE, to='props.properties')),
            ],
            options={
                'db_table': 'PropertyComment',
            },
        ),
    ]
