# Generated by Django 4.1.4 on 2023-02-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0005_alter_meterreading_pictureurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keys',
            name='id',
            field=models.AutoField(db_column='Id', db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='keys',
            name='types',
            field=models.TextField(blank=True, db_column='Types', db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='meterstypes',
            name='is_default',
            field=models.BooleanField(blank=True, db_column='IsDefault', db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='meterstypes',
            name='meters',
            field=models.TextField(blank=True, db_column='Meters', db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='condition',
            field=models.IntegerField(db_column='Condition', db_index=True),
        ),
        migrations.AlterField(
            model_name='propertycomment',
            name='comment',
            field=models.TextField(blank=True, db_column='Comment', db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertystatus',
            name='comment',
            field=models.TextField(blank=True, db_column='Comment', db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertytypes',
            name='id',
            field=models.AutoField(db_column='Id', db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='propertytypes',
            name='types',
            field=models.TextField(blank=True, db_column='Types', db_index=True, null=True),
        ),
    ]
