# Generated by Django 4.1.4 on 2023-02-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0006_alter_keys_id_alter_keys_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='signature',
            field=models.ImageField(blank=True, db_column='Signature', null=True, upload_to='props/signatures/'),
        ),
        migrations.AddField(
            model_name='properties',
            name='signature_name',
            field=models.CharField(blank=True, db_column='SignatureName', max_length=100, null=True),
        ),
    ]
