# Generated by Django 4.1.4 on 2023-02-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0007_properties_signature_properties_signature_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='condition',
            field=models.IntegerField(db_column='Condition', db_index=True, default=0),
        ),
    ]
