# Generated by Django 4.0.6 on 2022-07-21 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0007_meterstypes_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterstypes',
            name='isactive',
            field=models.BooleanField(blank=True, db_column='IsActive', null=True),
        ),
    ]
