# Generated by Django 4.1.4 on 2023-02-13 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0008_alter_properties_condition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyStatus',
        ),
    ]
