# Generated by Django 4.1.4 on 2023-02-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0009_delete_propertystatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='condition',
        ),
        migrations.AddField(
            model_name='properties',
            name='status',
            field=models.IntegerField(db_column='status', db_index=True, default=0),
        ),
    ]
