# Generated by Django 4.1.4 on 2023-02-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0010_remove_properties_condition_properties_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='condition',
            field=models.IntegerField(db_column='Condition', db_index=True, default=0),
        ),
    ]
