# Generated by Django 4.0.6 on 2022-07-24 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('props', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Furnitures',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('isactive', models.BooleanField(blank=True, db_column='IsActive', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('furniture', models.TextField(blank=True, db_column='Furniture', null=True)),
                ('is_default', models.BooleanField(blank=True, db_column='IsDefault', null=True)),
            ],
            options={
                'db_table': 'Furnitures',
            },
        ),
        migrations.CreateModel(
            name='Furnituresinrooms',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(db_column='Quantity')),
                ('comment', models.TextField(blank=True, db_column='Comment', null=True)),
                ('furnituresid', models.ForeignKey(db_column='FurnituresId', on_delete=django.db.models.deletion.CASCADE, to='rooms.furnitures')),
            ],
            options={
                'db_table': 'FurnituresInRooms',
            },
        ),
        migrations.CreateModel(
            name='Roomtypes',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('types', models.TextField(blank=True, db_column='Types', null=True)),
                ('pictureurl', models.ImageField(blank=True, db_column='PictureURL', null=True, upload_to='media/')),
            ],
            options={
                'db_table': 'RoomTypes',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roomtitle', models.TextField(blank=True, db_column='RoomTitle', null=True)),
                ('propertiesid', models.ForeignKey(db_column='PropertiesId', on_delete=django.db.models.deletion.CASCADE, to='props.properties')),
                ('roomtypesid', models.ForeignKey(db_column='RoomTypesId', on_delete=django.db.models.deletion.CASCADE, to='rooms.roomtypes')),
            ],
            options={
                'db_table': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='Roompictures',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.ImageField(blank=True, db_column='URL', null=True, upload_to='')),
                ('comment', models.TextField(blank=True, db_column='Comment', null=True)),
                ('roomsid', models.ForeignKey(db_column='RoomsId', on_delete=django.db.models.deletion.CASCADE, to='rooms.rooms')),
            ],
            options={
                'db_table': 'RoomPictures',
            },
        ),
        migrations.CreateModel(
            name='Furnituresinroomspictures',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.ImageField(blank=True, db_column='URL', null=True, upload_to='')),
                ('furnituresinroomsid', models.ForeignKey(db_column='FurnituresInRoomsId', on_delete=django.db.models.deletion.CASCADE, to='rooms.furnituresinrooms')),
            ],
            options={
                'db_table': 'FurnituresInRoomsPictures',
            },
        ),
        migrations.AddField(
            model_name='furnituresinrooms',
            name='roomsid',
            field=models.ForeignKey(db_column='RoomsId', on_delete=django.db.models.deletion.CASCADE, to='rooms.rooms'),
        ),
        migrations.AddField(
            model_name='furnitures',
            name='roomtypesid',
            field=models.ForeignKey(db_column='RoomTypesId', on_delete=django.db.models.deletion.CASCADE, to='rooms.roomtypes'),
        ),
        migrations.AddField(
            model_name='furnitures',
            name='user_id',
            field=models.ForeignKey(blank=True, db_column='userId', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
