# Generated by Django 4.0.6 on 2022-07-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roompictures',
            name='comment',
            field=models.TextField(blank=True, db_column='Comment', null=True),
        ),
        migrations.AddField(
            model_name='roomtypes',
            name='pictureurl',
            field=models.ImageField(blank=True, db_column='PictureURL', null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='furnituresinroomspictures',
            name='url',
            field=models.ImageField(blank=True, db_column='URL', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='roompictures',
            name='url',
            field=models.ImageField(blank=True, db_column='URL', null=True, upload_to=''),
        ),
    ]
