# Generated by Django 4.1.4 on 2023-03-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnituresinrooms',
            name='t_comment',
            field=models.TextField(blank=True, db_column='T_Comment', null=True),
        ),
        migrations.AddField(
            model_name='roompictures',
            name='t_comment',
            field=models.TextField(blank=True, db_column='T_Comment', null=True),
        ),
    ]
