# Generated by Django 4.0.6 on 2022-09-20 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0005_alter_meterreading_pictureurl'),
        ('rooms', '0002_remove_roomtypes_pictureurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='propertiesid',
            field=models.ForeignKey(blank=True, db_column='PropertiesId', null=True, on_delete=django.db.models.deletion.CASCADE, to='props.properties'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='roomtypesid',
            field=models.ForeignKey(blank=True, db_column='RoomTypesId', null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.roomtypes'),
        ),
    ]
