# Generated by Django 4.0.6 on 2022-07-20 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0006_meterstypes_is_default_and_more'),
        ('rooms', '0002_roompictures_comment_roomtypes_pictureurl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnitures',
            name='is_default',
            field=models.BooleanField(blank=True, db_column='IsDefault', null=True),
        ),
        migrations.AddField(
            model_name='furnituresinrooms',
            name='comment',
            field=models.TextField(blank=True, db_column='Comment', null=True),
        ),
        migrations.AlterField(
            model_name='furnitures',
            name='roomtypesid',
            field=models.ForeignKey(db_column='RoomTypesId', on_delete=django.db.models.deletion.CASCADE, to='rooms.roomtypes'),
        ),
        migrations.AlterField(
            model_name='furnituresinrooms',
            name='furnituresid',
            field=models.ForeignKey(db_column='FurnituresId', on_delete=django.db.models.deletion.CASCADE, to='rooms.furnitures'),
        ),
        migrations.AlterField(
            model_name='furnituresinrooms',
            name='roomsid',
            field=models.ForeignKey(db_column='RoomsId', on_delete=django.db.models.deletion.CASCADE, to='rooms.rooms'),
        ),
        migrations.AlterField(
            model_name='furnituresinroomspictures',
            name='furnituresinroomsid',
            field=models.ForeignKey(db_column='FurnituresInRoomsId', on_delete=django.db.models.deletion.CASCADE, to='rooms.furnituresinrooms'),
        ),
        migrations.AlterField(
            model_name='roompictures',
            name='roomsid',
            field=models.ForeignKey(db_column='RoomsId', on_delete=django.db.models.deletion.CASCADE, to='rooms.rooms'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='propertiesid',
            field=models.ForeignKey(db_column='PropertiesId', on_delete=django.db.models.deletion.CASCADE, to='props.properties'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='roomtypesid',
            field=models.ForeignKey(db_column='RoomTypesId', on_delete=django.db.models.deletion.CASCADE, to='rooms.roomtypes'),
        ),
    ]
