# Generated by Django 4.0.6 on 2022-09-20 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_rooms_propertiesid_alter_rooms_roomtypesid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnitures',
            name='isactive',
            field=models.BooleanField(blank=True, db_column='IsActive', default=True, null=True),
        ),
        migrations.AlterField(
            model_name='furnituresinrooms',
            name='furnituresid',
            field=models.ForeignKey(blank=True, db_column='FurnituresId', null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.furnitures'),
        ),
        migrations.AlterField(
            model_name='furnituresinrooms',
            name='roomsid',
            field=models.ForeignKey(blank=True, db_column='RoomsId', null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.rooms'),
        ),
    ]
