# Generated by Django 4.0.6 on 2022-07-21 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_furnitures_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnitures',
            name='isactive',
            field=models.BooleanField(blank=True, db_column='IsActive', null=True),
        ),
    ]
