# Generated by Django 4.0.6 on 2022-09-21 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_rename_url_furnituresinroomspictures_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roompictures',
            old_name='url',
            new_name='image',
        ),
    ]
