# Generated by Django 4.1.4 on 2023-02-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_rename_url_roompictures_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnitures',
            name='isactive',
            field=models.BooleanField(blank=True, db_column='IsActive', db_index=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='furnituresinroomspictures',
            name='id',
            field=models.AutoField(db_column='Id', db_index=True, primary_key=True, serialize=False),
        ),
    ]
