# Generated by Django 4.0.6 on 2022-07-14 00:32

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('isactive', models.BooleanField(db_column='IsActive')),
                ('regdate', models.CharField(blank=True, db_column='RegDate', max_length=10, null=True)),
                ('role_name', models.TextField(blank=True, choices=[('Tenant', 'Tenant'), ('Landlord', 'Lanlord')], db_column='RoleName', null=True)),
                ('comments', models.TextField(blank=True, db_column='Comments', null=True)),
            ],
            options={
                'db_table': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.TextField(blank=True, db_column='Email', null=True, unique=True)),
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_column='IsActive', default=False)),
                ('regdate', models.CharField(blank=True, db_column='RegDate', max_length=10, null=True)),
                ('type', models.IntegerField(db_column='Type', default=0)),
                ('firstname', models.TextField(blank=True, db_column='FirstName', null=True)),
                ('lastname', models.TextField(blank=True, db_column='LastName', null=True)),
                ('postalcode', models.TextField(blank=True, db_column='PostalCode', null=True)),
                ('fulladdress', models.TextField(blank=True, db_column='FullAddress', null=True)),
                ('phoneno', models.TextField(blank=True, db_column='PhoneNo', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Userinrole',
            fields=[
                ('roleid', models.ForeignKey(db_column='RoleId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='authen.roles')),
                ('isactive', models.BooleanField(db_column='IsActive')),
                ('regdate', models.CharField(blank=True, db_column='RegDate', max_length=10, null=True)),
                ('usersid', models.ForeignKey(db_column='UsersId', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserInRole',
                'unique_together': {('roleid', 'usersid')},
            },
        ),
    ]
