# Generated by Django 4.1.4 on 2023-03-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='postal_code',
            field=models.TextField(blank=True, db_column='PostalCode', null=True),
        ),
    ]
