# Generated by Django 4.1.4 on 2023-02-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, db_column='Email', db_index=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(db_column='Id', db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Tenant', 'Tenant'), ('Landlord', 'Lanlord'), ('Agency', 'Agency')], db_column='RoleName', db_index=True, max_length=10, null=True),
        ),
    ]
