# Generated by Django 4.0.6 on 2022-07-13 22:21

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('isactive', models.BooleanField(db_column='IsActive')),
                ('regdate', models.CharField(blank=True, db_column='RegDate', max_length=10, null=True)),
                ('rolename', models.TextField(blank=True, choices=[('Tenant', 'Tenant'), ('Landlord', 'Lanlord')], db_column='RoleName', null=True)),
                ('comments', models.TextField(blank=True, db_column='Comments', null=True)),
            ],
            options={
                'db_table': 'Roles',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='title',
        ),
        migrations.RemoveField(
            model_name='user',
            name='zip',
        ),
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=models.TextField(blank=True, db_column='FirstName', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fulladdress',
            field=models.TextField(blank=True, db_column='FullAddress', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='isactive',
            field=models.BooleanField(db_column='IsActive', default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.TextField(blank=True, db_column='LastName', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phoneno',
            field=models.TextField(blank=True, db_column='PhoneNo', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='postalcode',
            field=models.TextField(blank=True, db_column='PostalCode', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='regdate',
            field=models.CharField(blank=True, db_column='RegDate', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.IntegerField(db_column='Type', default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(blank=True, db_column='Email', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(db_column='Id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(db_column='Password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='Users',
        ),
        migrations.CreateModel(
            name='Userinrole',
            fields=[
                ('roleid', models.ForeignKey(db_column='RoleId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='authen.roles')),
                ('isactive', models.BooleanField(db_column='IsActive')),
                ('regdate', models.CharField(blank=True, db_column='RegDate', max_length=10, null=True)),
                ('usersid', models.ForeignKey(db_column='UsersId', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserInRole',
                'unique_together': {('roleid', 'usersid')},
            },
        ),
    ]
