# Generated by Django 4.0.6 on 2022-07-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(db_column='IsActive', default=True),
        ),
    ]
